/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function doInitialize(
  report: (err: Error | null, arg: SelectionInfo) => any,
  log: (err: Error | null, arg: string) => any,
): void

export interface SelectionInfo {
  content: string
  time: string
  lastMouseX: number
  lastMouseY: number
  selectionLeft: number
  selectionTop: number
}
