/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function doInitialize(
  args: number,
  report: (err: Error | null, arg: Array<SomeInfo>) => any,
  log: (err: Error | null, arg: string) => any,
): void

export interface SomeInfo {
  pname: string
  pid: number
  title: string
}
